# Define a certificate.
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.label }}-certificate
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.label }}-cert-secret
  issuerRef:
    name: {{ .Values.issuer }}
    kind: Issuer
  commonName: {{ .Values.ingress.host }} 
  dnsNames:
  - "{{ .Values.ingress.host }}"
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - "{{ .Values.ingress.host }}"