# Source: flask-app-config-helm-chart/templates/postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.label }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  user: {{ .Values.postgres.user | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
